version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: ci-database.cvcvuciqd08g.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 7wjVZJ+KvMaMuoMrqfuR++mHRKA
      WORDPRESS_DB_NAME: prod
    volumes:
      - ./wordpress:/var/www/html

volumes:
  wordpress:
  db:
